<a href="https://colab.research.google.com/github/mairaalejandrarueda1-ctrl/programacion1/blob/main/PARCIAL_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NOMBRE: MAIRA ALEJANDRA RUEDA MANRIQUE**

CODIGO: 2221977

**Parte II:**

Salidas de instrucciones asignadas (33/100): Registre la salida de cada una de las
instrucciones propuestas utilizando un ejemplo asignado. Ejecute los métodos
correspondientes y documente los resultados en un archivo .ipynb en Google Colab. Guarde
los archivos adicionales requeridos, respetando el formato indicado.

**Instrucción 1:**

 Genere un arreglo de NumPy con 50 números enteros aleatorios entre 1XY y 19Z,
donde XY corresponde a los dos últimos dígitos de la TI o CC y Z al último dígito de la edad.
Utilice el siguiente código:
np.random.seed(0)
datos = np.random.randint(1XY, 19Z, 50)

In [115]:
import numpy as np

In [116]:
np.random.seed(0)
datos = np.random.randint(109, 191, 50)

print(datos)

[153 156 173 176 176 118 130 145 179 121 167 174 148 155 190 146 134 186
 181 118 129 189 178 188 156 173 158 138 128 128 123 148 141 174 118 166
 141 140 183 132 144 184 164 137 143 109 109 145 162 114]

1. Implemente una filtración sobre el elemento datos e imprima el elemento con los valores
resultantes

In [117]:
np.unique(datos)

array([109, 114, 118, 121, 123, 128, 129, 130, 132, 134, 137, 138, 140,
       141, 143, 144, 145, 146, 148, 153, 155, 156, 158, 162, 164, 166,
       167, 173, 174, 176, 178, 179, 181, 183, 184, 186, 188, 189, 190])

2. Escale cada uno de los valores de datos utilizando una función lambda:

In [118]:
import pandas as pd
x = [109, 114, 118, 121, 123, 128, 129, 130, 132, 134, 137, 138, 140,
       141, 143, 144, 145, 146, 148, 153, 155, 156, 158, 162, 164, 166,
       167, 173, 174, 176, 178, 179, 181, 183, 184, 186, 188, 189, 190]
x = pd.DataFrame(x)
normalizar = lambda x: (x - x.mean()) / x.std()
resultado = normalizar(x)
print(resultado)

           0
0  -1.881560
1  -1.669599
2  -1.500030
3  -1.372854
4  -1.288070
5  -1.076109
6  -1.033717
7  -0.991324
8  -0.906540
9  -0.821756
10 -0.694579
11 -0.652187
12 -0.567403
13 -0.525011
14 -0.440226
15 -0.397834
16 -0.355442
17 -0.313050
18 -0.228265
19 -0.016305
20  0.068480
21  0.110872
22  0.195656
23  0.365225
24  0.450009
25  0.534793
26  0.577186
27  0.831539
28  0.873931
29  0.958715
30  1.043499
31  1.085892
32  1.170676
33  1.255460
34  1.297852
35  1.382637
36  1.467421
37  1.509813
38  1.552205

3. Implemente el método .describe() e interprete los resultados.

In [119]:
df. describe()

                0
count   39.000000
mean   153.384615
std     23.589265
min    109.000000
25%    135.500000
50%    153.000000
75%    175.000000
max    190.000000

4. Convierta el elemento datos en un DataFrame usando pandas. Imprima el elemento.

In [120]:
import pandas as pd
df = pd. DataFrame([109, 114, 118, 121, 123, 128, 129, 130, 132, 134, 137, 138, 140,
       141, 143, 144, 145, 146, 148, 153, 155, 156, 158, 162, 164, 166,
       167, 173, 174, 176, 178, 179, 181, 183, 184, 186, 188, 189, 190])
df

      0
0   109
1   114
2   118
3   121
4   123
5   128
6   129
7   130
8   132
9   134
10  137
11  138
12  140
13  141
14  143
15  144
16  145
17  146
18  148
19  153
20  155
21  156
22  158
23  162
24  164
25  166
26  167
27  173
28  174
29  176
30  178
31  179
32  181
33  183
34  184
35  186
36  188
37  189
38  190

5. Exporte los resultados a un archivo CSV llamado resultados.csv

In [121]:
from google.colab import files
import csv
datos = [109, 114, 118, 121, 123, 128, 129, 130, 132, 134, 137, 138, 140,
       141, 143, 144, 145, 146, 148, 153, 155, 156, 158, 162, 164, 166,
     167, 173, 174, 176, 178, 179, 181, 183, 184, 186, 188, 189, 190]


with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(datos)

files.download("datos.csv")

Instrucción 2: Construya un DataFrame en pandas con información de su elección. El
DataFrame debe cumplir con: (1) al menos 4 columnas (por ejemplo: nombre, edad, ingreso,
ciudad), (2) al menos 5 filas (registros) y (3) incluir datos numéricos y categóricos (o variable
cualitativa)
1. Muestre las primeras filas usando método .head()

In [14]:
import pandas as pd
df = pd. DataFrame({"Nombre": ["Ana", " luis", "Carlos", "Estiven", "Jhon"],
                    "Edad" : [23, 30, 25, 40, 32],
                    "Peso" : [60, 72, 90, 65, 88],
                    "Trabajo": ["Docente", "Medico", " Enfermero", "Policia", "Pediatra"]})
df

    Nombre  Edad  Peso     Trabajo
0      Ana    23    60     Docente
1     luis    30    72      Medico
2   Carlos    25    90   Enfermero
3  Estiven    40    65     Policia
4     Jhon    32    88    Pediatra

2. Seleccione una columna específica de su elección.

In [16]:
df["Trabajo"]

0       Docente
1        Medico
2     Enfermero
3       Policia
4      Pediatra
Name: Trabajo, dtype: object

3. Seleccione un conjunto de filas dadas condiciones específicas sobre valores de la columna.

In [18]:
df.iloc[3]

Nombre     Estiven
Edad            40
Peso            65
Trabajo    Policia
Name: 3, dtype: object

4. Cree una nueva columna que represente una transformación de una variable.

5. Agrupe los datos por una variable categórica usando el método .groupby(). Por ejemplo:

In [23]:
grupo = df.groupby("Trabajo")["Peso"].mean()
grupo

Trabajo
 Enfermero    90.0
Docente       60.0
Medico        72.0
Pediatra      88.0
Policia       65.0
Name: Peso, dtype: float64

6. Exporte el DataFrame final a un archivo CSV llamado datos_procesados.csv

In [43]:
from google.colab import files
import csv
datos = [
    ["Nombre", "Edad", "Peso", "Trabajo"],
    ["Ana",	23,	60,	"Docente"],
    ["luis",	30,	72,	"Medico"],
    ["Carlos",	25,	90,	"Enfermero"],
    ["Estiven",	40,	65,	"Policia"],
    ["Jhon",	32,	88,	"Pediatra"]
]

with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(datos)

files.download("datos.csv")

**Parte III:**

Proyecto: Una institución educativa busca analizar el desempeño académico de un mismo
grupo de estudiantes en dos evaluaciones distintas. Se plantea la posibilidad de que existan
diferencias en las calificaciones promedio entre ambas pruebas. Con este propósito, se requiere
desarrollar un paquete que permita realizar la comparación de los resultados para cualquier
conjunto de estudiantes.

In [60]:
import numpy as np
import pandas as pd

np.random.seed(0)

prueba_A = np.random.normal(loc=7.2, scale=0.4, size=53)
prueba_B = np.random.gamma(shape=306, scale=0.0229, size=53)

2. Construya un DataFrame en pandas que contenga ambas muestras.

In [ ]:
# CREAR UN CSV:
from google.colab import files
import csv
datos = [
    ["Nombre", "Edad", "Ciudad"],
    ["Ana", 25, "Bogotá"],
    ["Luis", 30, "Medellín"],
    ["Carlos", 28, "Cali"]
]

with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(datos)

files.download("datos.csv")

# CREAR MODULOS Y PAQUETES:

import os
os.makedirs("op", exist_ok=True)

%%writefile op/operaciones.py

# FUNCION LAMBDA
import pandas as pd
x = [1, 2, 3, 4]
x = pd.DataFrame(x)
normalizar = lambda x: (x - x.mean()) / x.std()
resultado = normalizar(x)
print(resultado)