<a href="https://colab.research.google.com/github/mairaalejandrarueda1-ctrl/programacion1/blob/main/tallerparcial2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [15]:
a = np.array(["a", "a", "d", "c", "f", "g"])

ORDENA LOS ELEMENTOS

In [16]:
np.unique(a)

array(['a', 'c', 'd', 'f', 'g'], dtype='<U1')

ELIMINA LAS REPETIDAS

In [17]:
np.concatenate([a, a])

array(['a', 'a', 'd', 'c', 'f', 'g', 'a', 'a', 'd', 'c', 'f', 'g'],
      dtype='<U1')

In [18]:
b = np.reshape(a, (3,2))
b

array([['a', 'a'],
       ['d', 'c'],
       ['f', 'g']], dtype='<U1')

In [19]:
import pandas as pd
b_pd = pd.DataFrame(b)
b_pd

   0  1
0  a  a
1  d  c
2  f  g

In [20]:
a[a != "b"]

array(['a', 'a', 'd', 'c', 'f', 'g'], dtype='<U1')

In [21]:
a[a > "b"]

array(['d', 'c', 'f', 'g'], dtype='<U1')

In [22]:
a[a == "letras"]

array([], dtype='<U1')

In [24]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 0], [0, 1]])
# PRODUCTO DE HADAMARD

In [25]:
A*B

array([[1, 0],
       [0, 4]])

In [26]:
np.array([A, B])

array([[[1, 2],
        [3, 4]],

       [[1, 0],
        [0, 1]]])

In [29]:
import pandas as pd
df = pd. DataFrame({"nombre": ["Ana", " luis", "Carlos"],
                    "edad" : [23, 30, 25],
                    "nota" : [4.5, 3.8, 4.2]})
df

   nombre  edad  nota
0     Ana    23   4.5
1    luis    30   3.8
2  Carlos    25   4.2

In [31]:
df["edad"]

0    23
1    30
2    25
Name: edad, dtype: int64

In [32]:
df.iloc[0] #FILA

nombre    Ana
edad       23
nota      4.5
Name: 0, dtype: object

In [33]:
df.loc[df["nombre"] == "Ana"]

  nombre  edad  nota
0    Ana    23   4.5

In [34]:
df.loc[df["edad"] > 25]

  nombre  edad  nota
1   luis    30   3.8

In [35]:
df["edad"] =df["edad"].astype(float)

In [36]:
df.sum()

nombre    Ana luisCarlos
edad                78.0
nota                12.5
dtype: object

In [37]:
df.min()

nombre     luis
edad       23.0
nota        3.8
dtype: object

In [38]:
df.max()

nombre    Carlos
edad        30.0
nota         4.5
dtype: object

In [40]:
df.describe()

            edad      nota
count   3.000000  3.000000
mean   26.000000  4.166667
std     3.605551  0.351188
min    23.000000  3.800000
25%    24.000000  4.000000
50%    25.000000  4.200000
75%    27.500000  4.350000
max    30.000000  4.500000

In [41]:
df[df["edad"] > 25]

  nombre  edad  nota
1   luis  30.0   3.8

In [43]:
df[df["nota"] > 4.0]

   nombre  edad  nota
0     Ana  23.0   4.5
2  Carlos  25.0   4.2

In [44]:
df["edad"].apply(lambda x: x + 1)

0    24.0
1    31.0
2    26.0
Name: edad, dtype: float64

In [47]:
import numpy as np
import pandas as pd

np.random.seed(123) # para guardar la semilla

In [51]:
datos = np.random.normal(loc = 4.0, scale = 0.5, size = 50)

df = pd.DataFrame({
    "nota": datos
})

In [52]:
df. describe()

            nota
count  50.000000
mean    4.020473
std     0.536967
min     2.938450
25%     3.582037
50%     4.018793
75%     4.518787
max     5.043557